---
- hosts: windowsservers
  gather_facts: no
  tasks:
    - name: "Join Windows Server 2 Domain"
      win_domain_membership:
        dns_domain_name: abc.com
        domain_admin_user: user@abc.com
        domain_admin_password: enterpass
        state: domain
      register: domain_state
    - win_reboot:
      when: domain_state.reboot_required